export const ROLE_TIERS = {
  fresher: {
    label: 'Fresher / Intern',
    salaryRange: '3–8 LPA',
    remoteSalary: '8–15 LPA',
    keyStrategy: 'Build portfolio, contribute to open source, get first full-time offer',
    primaryPlatforms: ['Internshala', 'LinkedIn', 'Naukri', 'HackerEarth', 'CodeChef Jobs'],
    outreachTarget: 'Senior engineers and team leads who hire interns',
    pitchStyle: 'Enthusiasm + learning speed + portfolio projects',
    resumeFocus: 'Projects, hackathons, college GPA, certifications, GitHub commits',
    connectionMessage: "Hi {name}, I'm a final-year CS student passionate about {skill}. I built {project} which does {value}. Would love to get your perspective on breaking into {company_type}.",
    hikeMultiplier: 'N/A (first job)',
    interviewFocus: ['Data structures basics', 'Algorithms', 'System design basics', 'HR behavioural'],
    autoConvFlow: {
      step1: "Hi {name}! I'm a {title} with a passion for {skill}. Your work at {company} caught my eye — would love to connect!",
      step2: "Thanks for connecting {name}! How did you get your first role at {company}? Any advice for someone just starting out?",
      step3: "That's incredibly helpful! I've been building {project} to showcase my skills. Is there any chance your team has an internship or entry-level opening?",
      referralAsk: "I know this is a big ask, but would you be willing to refer me for any opening at {company}? I'll make sure your referral reflects well.",
    },
  },
  junior: {
    label: 'Junior Engineer (0–2 yrs)',
    salaryRange: '6–15 LPA',
    remoteSalary: '15–30 LPA',
    keyStrategy: 'Level up skills fast, target product companies, avoid service company trap',
    primaryPlatforms: ['LinkedIn', 'Naukri', 'Instahyre', 'AngelList', 'Wellfound'],
    outreachTarget: 'Mid/Senior engineers at target companies, tech leads',
    pitchStyle: 'Growth trajectory + specific tech wins + ambition',
    resumeFocus: 'Specific tech stack, impact metrics, any promotions, course completions',
    connectionMessage: "Hi {name}, I'm a {role} with {X} months experience in {stack}. I recently {achievement}. Looking to grow at companies like {company} — would appreciate a chat or referral if there are openings.",
    hikeMultiplier: '1.5×–2.5×',
    interviewFocus: ['DSA medium', 'System design basics', 'Tech stack depth', 'Past projects'],
    autoConvFlow: {
      step1: "Hi {name}! Junior engineer here — {X} months in {stack}. Your experience at {company} is exactly the trajectory I'm targeting. Would love to connect!",
      step2: "Thanks for connecting! How does {company} evaluate junior to mid-level progression? I'm trying to understand what 'ready' looks like.",
      step3: "Really helpful! I've been working toward this — {achievement}. Is your team hiring? Would you be open to referring me?",
      referralAsk: "I've done deep research on {company}'s interview process. Would you be willing to refer me? I'll make the conversation count.",
    },
  },
  mid: {
    label: 'Mid-Level Engineer (2–4 yrs)',
    salaryRange: '12–28 LPA',
    remoteSalary: '25–60 LPA',
    keyStrategy: 'Specialise in 1–2 high-demand skills, target 4× hike with product companies',
    primaryPlatforms: ['LinkedIn', 'Naukri', 'Hirist', 'CutShort', 'Wellfound', 'Instahyre'],
    outreachTarget: 'Engineering Managers, Staff Engineers, CTOs at startups',
    pitchStyle: 'Ownership + measurable impact + specific domain depth',
    resumeFocus: 'Led/owned systems, scale numbers, performance improvements with %',
    connectionMessage: "Hi {name}, I have {X} years building {stack} at {current_company}. Recently {key_achievement_with_metric}. Exploring {target_role} opportunities at product companies — would love to connect.",
    hikeMultiplier: '2×–4×',
    interviewFocus: ['DSA medium-hard', 'System design', 'HLD', 'Leadership principles'],
    autoConvFlow: {
      step1: "Hi {name}! {X}-year engineer in {stack}. Your work at {company} caught my eye — would love to connect!",
      step2: "Thanks for connecting! I'm targeting senior roles at companies like {company}. What does the interview bar look like there?",
      step3: "Super helpful! I've been building toward this — {achievement}. Is your team hiring? Would you refer me?",
      referralAsk: "I've researched {company}'s engineering culture deeply. It's my top choice. Would you be willing to refer me for a senior {role} opening?",
    },
  },
  senior: {
    label: 'Senior Engineer (4–7 yrs)',
    salaryRange: '25–50 LPA',
    remoteSalary: '50–120 LPA',
    keyStrategy: 'Lead major systems, target staff/principal roles or management, remote-first',
    primaryPlatforms: ['LinkedIn', 'Blind', 'Wellfound', 'Turing', 'Toptal', 'Levels.fyi'],
    outreachTarget: 'CTOs, VPs Engineering, Directors at funded startups',
    pitchStyle: 'Scale, architecture decisions, team impact, cross-functional leadership',
    resumeFocus: 'Systems you architected, teams influenced, technical decisions and their business impact',
    connectionMessage: "Hi {name}, Senior {role} here who has {key_achievement_scale_architecture_team}. Exploring senior/staff opportunities where I can own critical systems. Open to a brief conversation?",
    hikeMultiplier: '1.5×–3× (higher base)',
    interviewFocus: ['System design hard', 'LLD', 'Leadership', 'Cross-team collaboration'],
    autoConvFlow: {
      step1: "Hi {name}! Senior SDE — {X} years in {stack}, led teams of {Y}. Your impact at {company} is exactly the scope I'm chasing. Would love to connect!",
      step2: "Thanks for connecting! I'm evaluating Staff IC vs EM track. How did you make that decision at {company}?",
      step3: "That's gold. I think {company}'s scale is exactly where I'd thrive. Is there a path to an interview? Would you be comfortable referring me?",
      referralAsk: "I've been deliberate about targeting {company} — it's my top choice. If you're open to it, a referral would mean the world. I'll make you look good.",
    },
  },
  staff: {
    label: 'Staff / Principal Engineer (7–12 yrs)',
    salaryRange: '50–100 LPA',
    remoteSalary: '100–200 LPA',
    keyStrategy: 'Drive org-level technical strategy, be known for a domain, write publicly',
    primaryPlatforms: ['LinkedIn', 'Blind', 'Levels.fyi', 'Executive recruiters', 'Referrals only'],
    outreachTarget: 'VPs Engineering, CTOs, Founders, Executive Recruiters',
    pitchStyle: 'Company-level impact, deep technical thought leadership, public presence',
    resumeFocus: 'Multi-year technical initiatives, patents, public talks, open source impact',
    connectionMessage: "Hi {name}, Staff Engineer specialising in {domain}. I recently published/spoke about {topic} and have been driving {initiative} at scale. Exploring principal/staff opportunities.",
    hikeMultiplier: '1.3×–2× (very high base)',
    interviewFocus: ['Architectural vision', 'Trade-off analysis', 'Influence without authority', 'Technical strategy'],
    autoConvFlow: {
      step1: "Hi {name}! Staff engineer in {technical_area}. Your work at {company} on {initiative} is exactly the scope I want to operate in. Would love to connect!",
      step2: "Thanks for connecting! I'm curious how {company} differentiates Staff vs Principal scope. I've been driving {initiative} — any thoughts?",
      step3: "Really appreciate the context. I think {company}'s {team} challenges map well to my background. Open to a call — or a referral if the fit seems right?",
      referralAsk: "I've mapped {company}'s technical org and believe I'm a strong fit for the {role} scope. Would you refer me? I'll send everything you need.",
    },
  },
  manager: {
    label: 'Engineering Manager (3–8 yrs total)',
    salaryRange: '30–70 LPA',
    remoteSalary: '70–150 LPA',
    keyStrategy: "Show team growth, delivery track record, use data to show your team's impact",
    primaryPlatforms: ['LinkedIn', 'Naukri', 'Executive search firms', 'Referrals'],
    outreachTarget: 'Directors, VPs, Founders, HR heads at fast-growing companies',
    pitchStyle: "Team growth, delivery speed, culture building, IC→Manager transition story",
    resumeFocus: 'Team size, attrition rate, delivery metrics, people promoted, cross-functional projects',
    connectionMessage: "Hi {name}, I manage a team of {N} engineers at {company}, focused on {area}. My team shipped {key_delivery} this year. Exploring EM roles at companies scaling from {X} to {Y} engineers.",
    hikeMultiplier: '1.5×–3×',
    interviewFocus: ['People management', 'Delivery and planning', 'Conflict resolution', 'Hiring bar'],
    autoConvFlow: {
      step1: "Hi {name}! Engineering Manager leading {N} engineers working on {product}. Your leadership at {company} is impressive. Would love to connect!",
      step2: "Thanks for connecting! I'm evaluating Director-level opportunities. How does {company} define scope at Director vs EM?",
      step3: "Really helpful! I think {company}'s scale is exactly where I want to lead next. Open to a conversation — or could you help me get in front of the right person?",
      referralAsk: "I'm ready for Director scope and {company} is my top choice. I have a strong track record — {achievement}. Would you refer me or make an introduction?",
    },
  },
  senior_manager: {
    label: 'Senior Manager / Group EM (8–13 yrs)',
    salaryRange: '50–100 LPA',
    remoteSalary: '100–200 LPA',
    keyStrategy: 'Multi-team ownership, build Director narrative, executive stakeholder credibility',
    primaryPlatforms: ['LinkedIn', 'Executive recruiters', 'CXO networking events', 'Referrals'],
    outreachTarget: 'VPs, CTOs, COOs, Board members',
    pitchStyle: 'Org-wide impact, multi-team coordination, business outcomes not just tech',
    resumeFocus: 'Multiple teams, budget ownership, business KPIs impacted, promotions given',
    connectionMessage: "Hi {name}, I lead {N} teams across {function} at {company}. We improved {metric} by {X}% this year. Exploring senior leadership roles at companies going through hypergrowth.",
    hikeMultiplier: '1.3×–2.5×',
    interviewFocus: ['Org design', 'Stakeholder alignment', 'Strategic planning', 'Budget', 'Executive presence'],
    autoConvFlow: {
      step1: "Hi {name}! Senior Manager leading {N} teams in {function} at {company}. Your VP/Director work is exactly the scope I'm targeting. Would love to connect!",
      step2: "Thanks for connecting! The Director→VP transition seems to require a shift from technical credibility to business impact framing. How did you navigate that?",
      step3: "That's a genuinely useful framework. I believe I'm ready for VP scope — would love to explore if {company} has any Director+ needs. Could you make an introduction?",
      referralAsk: "I'll be direct — {company} is where I want to make my next leap. My track record: {achievements}. Would you introduce me to your CHRO or the right hiring exec?",
    },
  },
  director: {
    label: 'Director of Engineering (10–18 yrs)',
    salaryRange: '80–180 LPA',
    remoteSalary: '150–350 LPA',
    keyStrategy: 'Own a business unit technically, be a thought leader publicly, target VP next',
    primaryPlatforms: ['Executive LinkedIn', 'Board referrals', 'CXO forums', 'Search firms'],
    outreachTarget: 'CTOs, CEOs, Investors, Board members, Executive search firms',
    pitchStyle: 'Business unit P&L impact, organisational transformation, strategic technical bets',
    resumeFocus: 'Revenue impact, large org building, strategic initiatives, external speaking',
    connectionMessage: "Hi {name}, I lead Engineering for {business_unit} at {company} — {N} engineers, {revenue_users_impacted}. Looking to join a company where I can scale engineering or drive a major transformation.",
    hikeMultiplier: '1.2×–2×',
    interviewFocus: ['Business strategy', 'Org transformation', 'Executive stakeholder management', 'Technical vision'],
    autoConvFlow: {
      step1: "Hi {name}! Director of Engineering at {company} — leading {N} engineers. Your CTO/VP work at {org} is exactly the scope I'm targeting next.",
      step2: "Thanks for connecting! The Director→VP transition feels like it requires more investor narrative and board exposure. How did you make that shift?",
      step3: "Really useful. I'd love to explore VP opportunities at the right inflection point company. Are there organisations in your network looking for strong technical leadership?",
      referralAsk: "I'll be direct — I'm ready for VP scope and selective. If you know of scale-ups or enterprises looking for a VP/CTO, I'd deeply appreciate an introduction.",
    },
  },
  vp: {
    label: 'VP / SVP Engineering (15+ yrs)',
    salaryRange: '150–400 LPA + equity',
    remoteSalary: '300–700 LPA + equity',
    keyStrategy: 'C-suite-adjacent positioning, board visibility, public thought leadership essential',
    primaryPlatforms: ['Executive search only', 'Board introductions', 'Investor networks', 'Conference speaking'],
    outreachTarget: 'CEOs, Board members, Investors, Peer VPs',
    pitchStyle: 'Company trajectory ownership, investor narrative, cultural transformation at scale',
    resumeFocus: 'Company outcomes (IPO prep, scale milestones, acquisitions), board presentations',
    connectionMessage: 'Direct outreach only via warm referrals or board introductions.',
    hikeMultiplier: 'Equity-driven',
    interviewFocus: ['Board presentations', 'Cultural transformation', 'M&A', 'IPO readiness', 'P&L ownership'],
    autoConvFlow: {
      step1: "Hi {name}! VP Engineering at {company} here — I own our full engineering org. Your CTO work at {org} is exactly the scope I'm targeting. Would love to connect.",
      step2: "Thanks for connecting! I'm exploring the next chapter — open to CTO, SVP, or select full-time opportunities at PE-backed or public cos.",
      step3: "I'd value a direct conversation. Do you know of any boards or PE portfolio companies looking for technical leadership at VP/CTO level?",
      referralAsk: "I'm selectively exploring. If you know of organisations where my background in {domain} at {scale} would be valuable, I'd appreciate a warm introduction.",
    },
  },
  c_suite: {
    label: 'CTO / CPO / CEO (20+ yrs)',
    salaryRange: '300+ LPA + equity',
    remoteSalary: 'Equity-driven ($500k+ USD)',
    keyStrategy: 'Become the face of a technology category, write/speak publicly, angel invest for network',
    primaryPlatforms: ['Headhunters only', 'Investor intros', 'YC/accelerator networks', 'Advisory boards'],
    outreachTarget: 'Investors, Founders, Board chairs, PE/VC partners',
    pitchStyle: 'Vision for the company, industry transformation, team-building philosophy at scale',
    resumeFocus: 'Company outcomes, equity events, industry influence, board seats, media coverage',
    connectionMessage: 'C-suite roles are never applied to — they require pre-existing relationships or board introductions.',
    hikeMultiplier: 'Equity and company outcomes',
    interviewFocus: ['Vision and strategy', 'Board dynamics', 'Fundraising', 'Culture at scale', 'Personal brand'],
    autoConvFlow: {
      step1: "Hi {name}! CTO at {company} here — selectively building my exec network. Your {achievement} at {org} caught my attention. Would love to connect.",
      step2: "Thanks for connecting! I'm exploring the next chapter — open to CTO-in-residence, advisory, or select full-time at PE-backed or public cos.",
      step3: "I'd value a direct conversation. Do you know of any boards or PE portfolio companies looking for technical leadership?",
      referralAsk: "I'm selectively exploring. If you know of organisations where my background would be valuable, I'd appreciate a warm introduction.",
    },
  },
} as const

export type RoleTier = keyof typeof ROLE_TIERS

export function getTierFromTitle(title: string): RoleTier {
  const t = title.toLowerCase()
  if (t.includes('cto') || t.includes('ceo') || t.includes('cpo') || t.includes('chief')) return 'c_suite'
  if (t.includes('vp') || t.includes('vice president') || t.includes('svp')) return 'vp'
  if (t.includes('director')) return 'director'
  if (t.includes('senior manager') || t.includes('group engineering') || t.includes('group em')) return 'senior_manager'
  if (t.includes('manager') || t.includes(' em ') || t.includes('engineering manager')) return 'manager'
  if (t.includes('staff') || t.includes('principal') || t.includes('distinguished')) return 'staff'
  if (t.includes('senior') || t.includes('sde 3') || t.includes('sde3') || t.includes('sr.')) return 'senior'
  if (t.includes('junior') || t.includes('entry') || t.includes('associate') || t.includes('sde 1') || t.includes('sde1')) return 'junior'
  if (t.includes('intern') || t.includes('fresher') || t.includes('trainee')) return 'fresher'
  return 'mid'
}
